# Generated by Django 3.2.15 on 2022-10-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Employee', 'Employee'), ('NewCustomer', 'NewCustomer')], max_length=255, null=True, verbose_name='Role'),
        ),
    ]
