# Generated by Django 3.2.15 on 2022-10-07 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('code', models.CharField(max_length=255, null=True, verbose_name='Code')),
                ('phoneno', models.BigIntegerField(null=True, verbose_name='Phone')),
                ('start_date', models.DateField(null=True, verbose_name='Start_date')),
                ('approvel_date', models.DateField(null=True, verbose_name='Approvel_date')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='Address')),
                ('state', models.CharField(max_length=255, null=True, verbose_name='State')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('City', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.city')),
                ('Place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.place')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('description', models.CharField(max_length=250, null=True, verbose_name=' Description ')),
                ('quantity', models.IntegerField(null=True, verbose_name='Quantity')),
                ('price', models.FloatField(null=True, verbose_name='Price')),
                ('image', models.ImageField(null=True, upload_to='Picture')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('state', models.CharField(max_length=255, null=True, verbose_name='State')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='Address')),
                ('phoneno', models.BigIntegerField(null=True, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('City', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.city')),
                ('Place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.place')),
                ('code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.company')),
            ],
        ),
    ]
