# Generated by Django 3.2.15 on 2022-10-07 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('phoneno', models.BigIntegerField(null=True, verbose_name='Phone')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='Address')),
                ('pincode', models.IntegerField(null=True, verbose_name='Pincode')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('customertype', models.CharField(blank=True, default='NewCustomer', max_length=100, null=True, verbose_name='CustomerType')),
                ('City', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.city')),
                ('Place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.place')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Order_refernce')),
                ('order_date', models.DateField(null=True, verbose_name='Orderdate')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='Address')),
                ('pincode', models.IntegerField(null=True, verbose_name='Pincode')),
                ('City', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.city')),
                ('Place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.place')),
            ],
        ),
        migrations.CreateModel(
            name='Orderline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True, verbose_name='Quanity')),
                ('amount', models.FloatField(null=True, verbose_name='amount')),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.food')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Pay_refernce')),
                ('pay', models.CharField(choices=[('googlepay', 'Googlepay'), ('phonepay', 'Phonepay'), ('paytym', 'Paytym')], max_length=250, null=True, verbose_name='Paytype')),
                ('paydate', models.DateField(null=True, verbose_name='Paydate')),
                ('amount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.orderline')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.customer')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.orderline'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.customer'),
        ),
    ]
