# Generated by Django 3.2.15 on 2022-10-08 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_customer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
