# Generated by Django 3.2.15 on 2022-10-16 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_remove_customer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='City',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Place',
        ),
    ]
